use_frameworks!

platform :ios, '8.0'

target 'FLYCodeTextView_Example' do
  pod 'FLYCodeTextView', :path => '../'

  target 'FLYCodeTextView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
